version: 2

name: "dbt_olist_ecom"                # Required project name
version: "1.0.0"                # Required version of the project
profile: "dbt_olist_ecom_profile"     # Required: matches a profile in profiles.yml

model-paths: ["models"]         # Required path to your models
seed-paths: ["seeds"]

models:
  dbt_olist_ecom:
    staging:
      +materialized: view
    marts:
      +materialized: table